---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: bugbash_sam_number

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 33
    option: 13
  - percentage: 33
    option: 15
  - percentage: 34
    option: 11

conditions: []
