---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: bugbash_sam_bool

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: bugbash_sam_tg
    flagValue: false
