---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: mwm-flag-1

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - flag:
          name: bugbash_sam_string
          value: ' MirrorPg'
    flagValue: false
