---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: bugbash_sam_number

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 33
    option: 13
  - percentage: 33
    option: 15
  - percentage: 34
    option: 11

conditions:
  - allOf:
      - allOf:
          - group:
              name: bugbash_sam_prop
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - property:
          name: bugbash_sam_string
          operator: is-undefined
    flagValue: 13
  - allOf:
      - flag:
          name: bugbash_sam_string
          value: ' MirrorPg'
    flagValue: 15
